### PR TITLE
Update console-image.bb

### PR DESCRIPTION
**Pull request by ZoranStojsavljevic**
ERROR: ParseError at /home/user/projects2/beaglebone-black/bbb-yocto/meta-bbb/images/console-image.bb:4: Could not include required file images/basic-dev-image.bb:--

### CODE REVIEW

**Comment by scottellis** [comment]
The basic-dev-image comes from the meta-jumpnow repo.

From the docs at https://jumpnowtek.com/beaglebone/BeagleBone-Systems-with-Yocto.html

  ...
  Clone the repositories
  ~$ git clone -b zeus git://git.yoctoproject.org/poky.git poky-zeus

  ~$ cd poky-zeus
  ~/poky-zeus$ git clone -b zeus git://git.openembedded.org/meta-openembedded
  ~/poky-zeus$ git clone -b zeus https://github.com/meta-qt5/meta-qt5.git
  ~/poky-zeus$ git clone -b zeus git://git.yoctoproject.org/meta-security.git

  These repositories shouldn’t need modifications other then periodic updates
  and can be reused for different projects or different boards.

  My own common meta-layer changing some upstream package defaults and adding
  a few custom recipes.

  ~/poky-zeus$ git clone -b zeus https://github.com/jumpnow/meta-jumpnow.git
  ...

The meta-jumpnow dependency is also listed in the meta-bbb/README.md and the
example meta-bbb/conf/bblayers.conf.sample


The meta-jumpnow layer is something I added to my zeus meta-layers. 

I just got tired of duplicating this stuff for all the boards in my build farm
(now 7 boards) that I build daily.

I understand that splitting it out like this provides no additional value for
people who only use one type of board.

And I would not do it this way for a customer with only one board.

But the jumpnow/meta-layers are just hobby projects for me these days and I
wanted to conserve time.

Best regards,
Scott

"Zoran Stojsavljevic" <notifications@github.com> said:

**Comment by ZoranStojsavljevic** [comment]
It is a bug, still. Does not matter what layers used for other boards.

I have my own setup script for BBB, so I fixed this issue there:
https://github.com/ZoranStojsavljevic/bbb-yocto/blob/master/bbb-yocto.sh

	## Fixing (zeus only) jumpnow/meta-bbb/console-image.bb: require images/basic-dev-image.bb
	cp meta-bbb/images/basic-image.bb meta-bbb/images/basic-dev-image.bb

Possible, other people will complain too. Well...

Best Regards,
Zoran

**Comment by scottellis** [comment]
Zoran, 

We have a misunderstanding.

meta-bbb, the zeus branch, has a new dependency on meta-jumpnow. 

That is where the basic-dev-image recipe can be found.

This is no different then meta-bbb also depending on meta-openembedded, meta-qt5 and meta-security.

There is no need to modify the meta-bbb console-image recipe if you clone meta-jumpnow and include it in your bblayers.conf.

There is also no need to create a meta-bbb/images/basic-dev-image.bb

Best regards,
Scott


"Zoran Stojsavljevic" <notifications@github.com> said:

**Comment by ZoranStojsavljevic** [comment]
U R correct. Understood, U added common class/layer, starting from ZEUS (to capture all the commonalities of Jumpnow boards maintained):
https://github.com/jumpnow/meta-jumpnow.git

The YOCTO designers need just to add it with your kernel overlay.

BTW, I did not add meta-security, it has some other dependencies, so for now I skipped it.

Closing the request, since it is not needed, not required. My bad!

Zoran

**Pull request closed without merging**
